version: '3'

services:
  abibliadigital:
    build: ./docker-api
    command: ["bash","/usr/src/api/start.sh"]
    ports:
      - "3000:3000"
    expose:
      - "3000"
    container_name: abibliadigital
    volumes:
      - ../abibliadigital:/usr/src/api
    depends_on:
      - abibliadigital-mongo
      - abibliadigital-redis

  abibliadigital-mongo:
    build: ./docker-mongo
    container_name: abibliadigital-mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ../mongo-abibliadigital/db/data:/data/db
      - ../mongo-abibliadigital/db/log:/var/log/mongodb

  abibliadigital-redis:
    image: "redis:alpine"
    container_name: abibliadigital-redis
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
       - $PWD/redis-data:/var/lib/redis
